const Chatsdata = [
  {
    Id: 1,
    name: 'Jason',
    status: 'Incoming',
    img: require('../assets/images/R.png'),
    Date: '27/12/23',
  },
  {
    Id: 2,
    name: 'Jason',
    status: 'Outgoing',
    img: require('../assets/images/R.png'),
    Date: '07/12/23',
  },
  {
    Id: 3,
    name: 'Jason',
    status: 'Missed',
    img: require('../assets/images/R.png'),
    Date: '27/11/23',
  },
  {
    Id: 4,
    name: 'Jason',
    status: 'Incoming',
    img: require('../assets/images/R.png'),
    Date: '27/10/23',
  },
  {
    Id: 5,
    name: 'Jason',
    status: 'Outgoing',
    img: require('../assets/images/R.png'),
    Date: '02/10/23',
  },
  {
    Id: 6,
    name: 'Jason',
    status: 'Missed',
    img: require('../assets/images/R.png'),
    Date: '27/09/23',
  },
  {
    Id: 7,
    name: 'Jason',
    status: 'Incoming',
    img: require('../assets/images/R.png'),
    Date: '07/09/23',
  },
  {
    Id: 8,
    name: 'Jason',
    status: 'Outgoing',
    img: require('../assets/images/R.png'),
    Date: '27/08/23',
  },
  {
    Id: 9,
    name: 'Jason',
    status: 'Missed',
    img: require('../assets/images/R.png'),
    Date: '02/08/23',
  },
  {
    Id: 10,
    name: 'Jason',
    status: 'Incoming',
    img: require('../assets/images/R.png'),
    Date: '27/07/23',
  },
  {
    Id: 11,
    name: 'Jason',
    status: 'Outgoing',
    img: require('../assets/images/R.png'),
    Date: '07/07/23',
  },
  {
    Id: 12,
    name: 'Jason',
    status: 'Missed',
    img: require('../assets/images/R.png'),
    Date: '27/06/23',
  },
];
export default Chatsdata;
