const Chatsdata = [
  {
    Id:1,
    name: 'Jason',
    message: 'Hey there!',
    img: require('../assets/images/R.png'),
    Date: '27/12/23',
  },
  {
    Id:2,
    name: 'Jason',
    message: 'Hey there!',
    img: require('../assets/images/R.png'),
    Date: '27/12/23',
  },
  {
    Id:3,
    name: 'Jason',
    message: 'Hey there!',
    img: require('../assets/images/R.png'),
    Date: '27/12/23',
  },
  {
    Id:4,
    name: 'Jason',
    message: 'Hey there!',
    img: require('../assets/images/R.png'),
    Date: '27/12/23',
  },
  {
    Id:5,
    name: 'Jason',
    message: 'Hey there!',
    img: require('../assets/images/R.png'),
    Date: '27/12/23',
  },
  {
    Id:6,
    name: 'Jason',
    message: 'Hey there!',
    img: require('../assets/images/R.png'),
    Date: '27/12/23',
  },
  {
    Id:7,
    name: 'Jason',
    message: 'Hey there!',
    img: require('../assets/images/R.png'),
    Date: '27/12/23',
  },
  {
    Id:8,
    name: 'Jason',
    message: 'Hey there!',
    img: require('../assets/images/R.png'),
    Date: '27/12/23',
  },
  {
    Id:9,
    name: 'Jason',
    message: 'Hey there!',
    img: require('../assets/images/R.png'),
    Date: '27/12/23',
  },
  {
    Id:10,
    name: 'Jason',
    message: 'Hey there!',
    img: require('../assets/images/R.png'),
    Date: '27/12/23',
  },
  {
    Id:11,
    name: 'Jason',
    message: 'Hey there!',
    img: require('../assets/images/R.png'),
    Date: '27/12/23',
  },
  {
    Id:12,
    name: 'Jason',
    message: 'Hey there!',
    img: require('../assets/images/R.png'),
    Date: '27/12/23',
  },
  {
    Id:13,
    name: 'Jason',
    message: 'Hey there!',
    img: require('../assets/images/R.png'),
    Date: '27/12/23',
  },
  {
    Id:14,
    name: 'Jason',
    message: 'Hey there!',
    img: require('../assets/images/R.png'),
    Date: '27/12/23',
  },
];
export default Chatsdata;
